name: Deploy to server

on: push

jobs:
  first_job:
    name: Print a message
    runs-on: ubuntu-latest
    env: 
      NAME: Armando
    steps:
      - name: Hello World
        run: echo "Hello World ${{ env.NAME }}"
  
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - name: Github Ref
        run: echo "Github ref ${{ github.ref }}" 